version: 2.1
jobs:
  build-test-ingest:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/iot-laundry
    steps:
      - checkout
      - run: echo "ingest"

  build-test-nodejs:
    docker:
      - image: circleci/node:10
    working_directory: ~/iot-laundry
    steps:
      - checkout
      - run: echo "nodejs"

  build-test-python:
    docker:
      - image: circleci/python:3
    working_directory: ~/iot-laundry
    steps:
      - checkout
      - run: echo "python"