apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: svc-fanout
spec:
  rules:
  - host: laundry.minikube
    http:
      paths:
      - path: /
        backend:
          serviceName: svc-web
          servicePort: 8888
      - path: /stats
        backend:
          serviceName: svc-web
          servicePort: 8888
      - path: /img
        backend:
          serviceName: svc-ingest
          servicePort: 8885
      - path: /predict
        backend:
          serviceName: svc-predict
          servicePort: 5000
      - path: /storePredict
        backend:
          serviceName: svc-track
          servicePort: 8889
