apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-web
  template:
    metadata:
      labels:
        app: svc-web
    spec:
      containers:
      - name: svc-web
        image: kenahrens/svc-web
        imagePullPolicy: Never
        livenessProbe:
          httpGet:
            path: /stats
            port: 8888
          initialDelaySeconds: 5
          periodSeconds: 10
        ports:
        - containerPort: 8888
          protocol: TCP
        env:
        - name: PORT
          value: "8888"
        - name: NEW_RELIC_APP_NAME
          value: "IoT Laundry Server"
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: newrelic
              key: NEW_RELIC_LICENSE_KEY
        volumeMounts:
        - name: local-volume
          mountPath: /app/archive
      volumes:
      - name: local-volume
        hostPath:
          path: /hosthome/kahrens/Pictures/archive
          type: Directory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-predict
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-predict
  template:
    metadata:
      labels:
        app: svc-predict
    spec:
      containers:
      - name: svc-predict
        image: kenahrens/svc-predict
        imagePullPolicy: Never
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: newrelic
              key: NEW_RELIC_LICENSE_KEY
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-track
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-track
  template:
    metadata:
      labels:
        app: svc-track
    spec:
      containers:
      - name: svc-track
        image: kenahrens/svc-track
        imagePullPolicy: Never
        livenessProbe:
          httpGet:
            path: /
            port: 8889
          initialDelaySeconds: 5
          periodSeconds: 10
        ports:
        - containerPort: 8889
          protocol: TCP
        env:
        - name: PORT
          value: "8889"
        - name: NEW_RELIC_APP_NAME
          value: "svc-track"
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: newrelic
              key: NEW_RELIC_LICENSE_KEY
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-ingest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-ingest
  template:
    metadata:
      labels:
        app: svc-ingest
    spec:
      containers:
      - name: svc-ingest
        image: kenahrens/ingest
        imagePullPolicy: Never
        livenessProbe:
          httpGet:
            path: /
            port: 8885
          initialDelaySeconds: 5
          periodSeconds: 10
        ports:
        - containerPort: 8885
          protocol: TCP
        env:
        - name: NEW_RELIC_APP_NAME
          value: "svc-ingest"
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: newrelic
              key: NEW_RELIC_LICENSE_KEY