apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-web
  template:
    metadata:
      labels:
        app: svc-web
    spec:
      containers:
      - name: svc-web
        image: kenahrens/svc-web
        imagePullPolicy: Never
        livenessProbe:
          httpGet:
            path: /stats
            port: 8888
          initialDelaySeconds: 5
          periodSeconds: 10
        ports:
        - containerPort: 8888
          protocol: TCP
        env:
        - name: PORT
          value: "8888"
        - name: NEW_RELIC_APP_NAME
          value: "IoT Laundry Server"
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: newrelic
              key: NEW_RELIC_LICENSE_KEY
        volumeMounts:
        - name: local-volume
          mountPath: /app/archive
      volumes:
      - name: local-volume
        hostPath:
          path: /hosthome/kahrens/Pictures/archive
          type: Directory
